# Generated by Django 2.2.6 on 2019-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(choices=[('대한항공', '대한항공'), ('아시아나', '아시아나항공')], max_length=20)),
                ('airport', models.CharField(max_length=50)),
                ('arrived', models.CharField(max_length=50)),
                ('date', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('day', models.CharField(max_length=10, null=True)),
                ('delayRate', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
