# Generated by Django 2.2.6 on 2019-10-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intimeWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airFln', models.TextField()),
                ('airline', models.TextField()),
                ('airport', models.TextField()),
                ('arrived', models.TextField()),
                ('boarding', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Web',
        ),
    ]
