# Generated by Django 2.2.6 on 2019-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intimeWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('대한항공', '대한항공'), ('아시아나', '아시아나항공'), ('에어부산', '에어부산'), ('에어필립', '에어필립'), ('티웨이항공', '티웨이항공'), ('제주항공', '제주항공'), ('이스타항공', '이스타항공'), ('진에어', '진에어')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport',
            field=models.CharField(choices=[('제주공항', '제주공항'), ('김포공항', '김포공항')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrived',
            field=models.CharField(choices=[('제주공항', '제주공항'), ('김포공항', '김포공항')], max_length=50),
        ),
    ]
