# Generated by Django 2.2.6 on 2019-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intimeWeb', '0002_auto_20191031_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='day',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='time',
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(),
        ),
    ]
