# Generated by Django 2.2.6 on 2019-10-28 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intimeWeb', '0003_auto_20191028_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.AlterField(
            model_name='flight',
            name='airFln',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='schTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 14, 40, 45, 518147, tzinfo=utc)),
        ),
    ]
