# Generated by Django 2.2.6 on 2019-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intimeWeb', '0004_auto_20191031_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('대한항공', '대한항공'), ('아시아나항공', '아시아나항공'), ('에어부산', '에어부산'), ('에어필립', '에어필립'), ('티웨이항공', '티웨이항공'), ('제주항공', '제주항공'), ('이스타항공', '이스타항공'), ('진에어', '진에어')], max_length=20),
        ),
    ]
