# Generated by Django 2.2.6 on 2019-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intimeWeb', '0005_auto_20191031_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airport',
            field=models.CharField(choices=[('제주', '제주'), ('김포', '김포')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrived',
            field=models.CharField(choices=[('제주', '제주'), ('김포', '김포')], max_length=50),
        ),
    ]
